import {
  BarChart3,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  Camera,
  Clock,
  Coffee,
  CreditCard,
  Dumbbell,
  FileText,
  Gauge,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Home,
  Languages,
  Laptop,
  Mail,
  Megaphone,
  Mic,
  Palette,
  PenTool,
  PhoneCall,
  PieChart,
  PiggyBank,
  Repeat,
  Rocket,
  Shield,
  Shirt,
  ShoppingCart,
  Sparkles,
  Sunrise,
  Target,
  TrendingUp,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wrench,
} from 'lucide-react-native';

import { colors } from '@/constants/theme';

/** iconKey (from the goal catalogue) → lucide icon component. */
const ICONS = {
  // Catalogue icon keys
  'bar-chart': BarChart3,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  calculator: Calculator,
  camera: Camera,
  clock: Clock,
  coffee: Coffee,
  'credit-card': CreditCard,
  dumbbell: Dumbbell,
  'file-text': FileText,
  gauge: Gauge,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  languages: Languages,
  laptop: Laptop,
  mail: Mail,
  megaphone: Megaphone,
  mic: Mic,
  palette: Palette,
  'pen-tool': PenTool,
  'phone-call': PhoneCall,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  repeat: Repeat,
  rocket: Rocket,
  shield: Shield,
  shirt: Shirt,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  sunrise: Sunrise,
  target: Target,
  'trending-up': TrendingUp,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wrench: Wrench,

  // Legacy keys used by the static src/data/goals.ts catalogue
  debt: CreditCard,
  investing: TrendingUp,
  saving: PiggyBank,
  budgeting: Wallet,
  income: Briefcase,
} as const;

type Props = { iconKey: string; size?: number; color?: string };

export function GoalIcon({ iconKey, size = 22, color = colors.brandGreen }: Props) {
  const Icon = ICONS[iconKey as keyof typeof ICONS] ?? Target;
  return <Icon size={size} color={color} />;
}
